<a href="https://colab.research.google.com/github/AdityaMall1093/ML-Learning/blob/main/house_price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt

In [50]:
df=pd.read_csv("/content/House_Prices.csv")

In [51]:
df.head()

   Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0     1  114300  1790         2          2       2    No         East
1     2  114200  2030         4          2       3    No         East
2     3  114800  1740         3          2       1    No         East
3     4   94700  1980         3          2       3    No         East
4     5  119800  2130         3          3       3    No         East

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Home          128 non-null    int64
 1   Price         128 non-null    int64
 2   SqFt          128 non-null    int64
 3   Bedrooms      128 non-null    int64
 4   Bathrooms     128 non-null    int64
 5   Offers        128 non-null    int64
 6   Brick         128 non-null    object
 7   Neighborhood  128 non-null    object
dtypes: int64(6), object(2)
memory usage: 8.1+ KB

In [53]:
df.describe()

,Home,Price,SqFt,Bedrooms,Bathrooms,Offers
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,64.500000,130427.343750,2000.937500,3.023438,2.445312,2.578125
std,37.094474,26868.770371,211.572431,0.725951,0.514492,1.069324
min,1.000000,69100.000000,1450.000000,2.000000,2.000000,1.000000
25%,32.750000,111325.000000,1880.000000,3.000000,2.000000,2.000000
50%,64.500000,125950.000000,2000.000000,3.000000,2.000000,3.000000
75%,96.250000,148250.000000,2140.000000,3.000000,3.000000,3.000000
max,128.000000,211200.000000,2590.000000,5.000000,4.000000,6.000000

In [55]:
df.columns

Index(['Home', 'Price', 'SqFt', 'Bedrooms', 'Bathrooms', 'Offers', 'Brick',
       'Neighborhood'],
      dtype='object')

In [56]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [57]:
df['Brick'] = le.fit_transform(df['Brick'])
df['Neighborhood'] = le.fit_transform(df['Neighborhood'])

In [58]:
df.head()

   Home   Price  SqFt  Bedrooms  Bathrooms  Offers  Brick  Neighborhood
0     1  114300  1790         2          2       2      0             0
1     2  114200  2030         4          2       3      0             0
2     3  114800  1740         3          2       1      0             0
3     4   94700  1980         3          2       3      0             0
4     5  119800  2130         3          3       3      0             0

In [59]:
df=df.astype(int)

In [61]:
df.head()

   Home   Price  SqFt  Bedrooms  Bathrooms  Offers  Brick  Neighborhood
0     1  114300  1790         2          2       2      0             0
1     2  114200  2030         4          2       3      0             0
2     3  114800  1740         3          2       1      0             0
3     4   94700  1980         3          2       3      0             0
4     5  119800  2130         3          3       3      0             0

In [62]:
X=df.drop('Price',axis=1)
y=df['Price']

In [65]:
from sklearn.model_selection import train_test_split

X_train,X_test ,y_train,y_test=train_test_split(X,y,test_size=0.2,
                                                random_state=42)

In [77]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [78]:
y_pred=model.predict(X_test)

In [79]:
y_pred

array([112264.49848151,  94265.09971833, 158965.72574221, 136851.96451566,
       151259.75273068, 138313.03881184, 144266.42418726,  88690.32788201,
       177413.76445713, 132057.76876459, 166829.64768097,  98174.42295584,
       127529.73425374, 124921.16934128, 143767.23784272, 133640.49194957,
       114909.05691247, 134597.0655048 , 125652.75425548,  78247.51011065,
       122761.19337082, 128549.31220649, 130109.82614855, 123574.20096165,
       163094.02024748,  94280.4110177 ])

In [80]:
y_test

55     125700
40     106600
19     167200
31     112300
98     145500
56     140900
69     165600
104     82300
81     184300
26     137000
94     160600
27      99300
64     130300
4      119800
96     133300
113    115700
36     117500
80     143400
125    113500
84      90500
18     111400
10     132500
118    150200
11     123000
105    146900
45     103200
Name: Price, dtype: int64

In [83]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 9499.965442507395
MSE: 130338013.2511131
RMSE: 11416.567489885614
R2 Score: 0.7788628120196363

In [92]:
from sklearn.tree import DecisionTreeRegressor

model_dt = DecisionTreeRegressor(random_state=42)

model_dt.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [93]:
y_pred_dt = model_dt.predict(X_test)

In [90]:
y_test

55     125700
40     106600
19     167200
31     112300
98     145500
56     140900
69     165600
104     82300
81     184300
26     137000
94     160600
27      99300
64     130300
4      119800
96     133300
113    115700
36     117500
80     143400
125    113500
84      90500
18     111400
10     132500
118    150200
11     123000
105    146900
45     103200
Name: Price, dtype: int64

In [94]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred_dt)
mse = mean_squared_error(y_test, y_pred_dt)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_dt)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 17096.153846153848
MSE: 431495000.0
RMSE: 20772.457726518543
R2 Score: 0.26790666400792207

In [95]:
from sklearn.ensemble import RandomForestRegressor

model_rf = RandomForestRegressor(random_state=42)

model_rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [96]:
y_pred_rf = model_rf.predict(X_test)

In [98]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred_rf)
mse = mean_squared_error(y_test, y_pred_rf)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_rf)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 10174.192307692309
MSE: 182963672.8846154
RMSE: 13526.406503007936
R2 Score: 0.6895758105019494

In [102]:
from xgboost import XGBRegressor

model_xgb = XGBRegressor(random_state=42)

model_xgb.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [103]:
y_pred_xgb = model_xgb.predict(X_test)

In [104]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred_xgb)
mse = mean_squared_error(y_test, y_pred_xgb)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_xgb)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 12193.5419921875
MSE: 256690672.0
RMSE: 16021.568961871368
R2 Score: 0.5644873380661011