<a href="https://colab.research.google.com/github/AdityaMall1093/ML-Learning/blob/main/NLPipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [95]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [96]:
df=pd.read_csv('train.txt',sep=';',header=None,names=['text','emotion'])

In [97]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   text     16000 non-null  object
 1   emotion  16000 non-null  object
dtypes: object(2)
memory usage: 250.1+ KB

In [99]:
df.describe()

                                                     text emotion
count                                               16000   16000
unique                                              15969       6
top     im still not sure why reilly feels the need to...     joy
freq                                                    2    5362

In [100]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [101]:
unique_emotion=df['emotion'].unique()
emotion_number={}
i=0
for emo in unique_emotion:
    emotion_number[emo]=i
    i +=1
df['emotion']=df['emotion'].map(emotion_number)

In [102]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [103]:
df['text'] = df['text'].apply(lambda x: x.lower())

In [104]:
import string

def remove_punc(text):
    if isinstance(text, str):
        return text.translate(str.maketrans('', '', string.punctuation))
    return text

df['text'] = df['text'].apply(remove_punc)

In [105]:
def remove_number(txt):
    new = ""

    for i in txt:
        if not i.isdigit():
            new = new + i

    return new

df['text'] = df['text'].apply(remove_number)

In [106]:
def remove_emojis(txt):
   new=""

   for i in txt:
    if i.isascii():
       new=new+i

   return new

df['text']=df['text'].apply(remove_emojis)

In [107]:
import nltk

In [108]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [109]:
stop_words = set(stopwords.words('english'))

In [110]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [111]:
len(stop_words)

198

In [112]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [113]:
def remove(txt):
  words=txt.split()
  cleaned=[]
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return ''.join(cleaned)

In [114]:
df['text']=df['text'].apply(remove)

In [115]:
df.loc[1]['text']

'gofeelinghopelessdamnedhopefularoundsomeonecaresawake'

In [116]:
df.head()

                                                text  emotion
0                                didntfeelhumiliated        0
1  gofeelinghopelessdamnedhopefularoundsomeonecar...        0
2                imgrabbingminutepostfeelgreedywrong        1
3     everfeelingnostalgicfireplaceknowstillproperty        2
4                                     feelinggrouchy        1

In [117]:
from re import X
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.2, random_state=42)

In [118]:
X_train

676      referscoursethoughcanthelpfeelingsomehowironic...
12113                     imstartingfeelimsufferingfatigue
7077     feellikeprobablywouldlikedbooklittlebitsimples...
13005                                    reallyfeelawkward
12123    imfeelinglittlegrumpytodaylameweatherteasegotw...
                               ...
13418       loveleavereaderfeelingconfusedslightlydeceived
5390                                          feeldelicate
860                             startingfeellittlestressed
15795                  feelstressedtiredwornshapeneglected
7270               feelsomeonerudewronglydonesomethinglose
Name: text, Length: 12800, dtype: object

In [119]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [120]:
bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

In [121]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [122]:
nb_classifier = MultinomialNB()
nb_classifier.fit(X_train_bow, y_train)

MultinomialNB()

In [123]:
pred_bow = nb_classifier.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))
print(classification_report(y_test, pred_bow))

0.3234375
              precision    recall  f1-score   support

           0       0.92      0.01      0.02       946
           1       1.00      0.00      0.00       427
           2       0.00      0.00      0.00       296
           3       0.00      0.00      0.00       113
           4       1.00      0.01      0.01       397
           5       0.32      1.00      0.49      1021

    accuracy                           0.32      3200
   macro avg       0.54      0.17      0.09      3200
weighted avg       0.63      0.32      0.16      3200

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [124]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [125]:
nb2_model=MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [126]:
y_pred=nb2_model.predict(X_test_tfidf)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.3234375
              precision    recall  f1-score   support

           0       0.92      0.01      0.02       946
           1       1.00      0.00      0.00       427
           2       0.00      0.00      0.00       296
           3       0.00      0.00      0.00       113
           4       1.00      0.01      0.01       397
           5       0.32      1.00      0.49      1021

    accuracy                           0.32      3200
   macro avg       0.54      0.17      0.09      3200
weighted avg       0.63      0.32      0.16      3200

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [127]:
from sklearn.linear_model import LogisticRegression

In [128]:
log_reg=LogisticRegression(max_iter=1000)
log_reg.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [129]:
log_pred=log_reg.predict(X_test_tfidf)
print(accuracy_score(y_test,log_pred))
print(classification_report(y_test,log_pred))

0.3246875
              precision    recall  f1-score   support

           0       0.92      0.01      0.02       946
           1       0.71      0.01      0.02       427
           2       0.00      0.00      0.00       296
           3       0.00      0.00      0.00       113
           4       1.00      0.01      0.01       397
           5       0.32      1.00      0.49      1021

    accuracy                           0.32      3200
   macro avg       0.49      0.17      0.09      3200
weighted avg       0.59      0.32      0.17      3200

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))