<a href="https://colab.research.google.com/github/AdityaMall1093/ML-Learning/blob/main/supervised_learing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
#Supervised Learning

In [70]:
#import lib
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [71]:
df = pd.read_csv("/content/Titanic.csv")

In [72]:
df.head()

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   891 non-null    int64
 1   survived     891 non-null    int64
 2   pclass       891 non-null    int64
 3   sex          891 non-null    object
 4   age          714 non-null    float64
 5   sibsp        891 non-null    int64
 6   parch        891 non-null    int64
 7   fare         891 non-null    float64
 8   embarked     889 non-null    object
 9   class        891 non-null    object
 10  who          891 non-null    object
 11  adult_male   891 non-null    bool
 12  deck         203 non-null    object
 13  embark_town  889 non-null    object
 14  alive        891 non-null    object
 15  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(5), object(7)
memory usage: 99.3+ KB

In [74]:
df.describe()

,Unnamed: 0,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,445.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,0.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,222.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,445.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,667.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,890.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [75]:
df.columns

Index(['Unnamed: 0', 'survived', 'pclass', 'sex', 'age', 'sibsp', 'parch',
       'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [76]:
df.drop([ 'deck','class','who','embark_town','alive'], axis=1, inplace=True)

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  891 non-null    int64
 1   survived    891 non-null    int64
 2   pclass      891 non-null    int64
 3   sex         891 non-null    object
 4   age         714 non-null    float64
 5   sibsp       891 non-null    int64
 6   parch       891 non-null    int64
 7   fare        891 non-null    float64
 8   embarked    889 non-null    object
 9   adult_male  891 non-null    bool
 10  alone       891 non-null    bool
dtypes: bool(2), float64(2), int64(5), object(2)
memory usage: 64.5+ KB

In [78]:
df['age'].fillna(df['age'].mean(),inplace=True)

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  891 non-null    int64
 1   survived    891 non-null    int64
 2   pclass      891 non-null    int64
 3   sex         891 non-null    object
 4   age         891 non-null    float64
 5   sibsp       891 non-null    int64
 6   parch       891 non-null    int64
 7   fare        891 non-null    float64
 8   embarked    889 non-null    object
 9   adult_male  891 non-null    bool
 10  alone       891 non-null    bool
dtypes: bool(2), float64(2), int64(5), object(2)
memory usage: 64.5+ KB

In [80]:
df.dropna(subset=['embarked'],inplace=True)

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  889 non-null    int64
 1   survived    889 non-null    int64
 2   pclass      889 non-null    int64
 3   sex         889 non-null    object
 4   age         889 non-null    float64
 5   sibsp       889 non-null    int64
 6   parch       889 non-null    int64
 7   fare        889 non-null    float64
 8   embarked    889 non-null    object
 9   adult_male  889 non-null    bool
 10  alone       889 non-null    bool
dtypes: bool(2), float64(2), int64(5), object(2)
memory usage: 71.2+ KB

In [82]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [83]:
df.head()

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,alone
0,0,0,3,male,22.0,1,0,7.2500,S,True,False
1,1,1,1,female,38.0,1,0,71.2833,C,False,False
2,2,1,3,female,26.0,0,0,7.9250,S,False,True
3,3,1,1,female,35.0,1,0,53.1000,S,False,False
4,4,0,3,male,35.0,0,0,8.0500,S,True,True

In [84]:

df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])

In [85]:
df.head()

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,alone
0,0,0,3,1,22.0,1,0,7.2500,2,True,False
1,1,1,1,0,38.0,1,0,71.2833,0,False,False
2,2,1,3,0,26.0,0,0,7.9250,2,False,True
3,3,1,1,0,35.0,1,0,53.1000,2,False,False
4,4,0,3,1,35.0,0,0,8.0500,2,True,True

In [86]:
df=df.astype(int)

In [87]:

df.head()

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,alone
0,0,0,3,1,22,1,0,7,2,1,0
1,1,1,1,0,38,1,0,71,0,0,0
2,2,1,3,0,26,0,0,7,2,0,1
3,3,1,1,0,35,1,0,53,2,0,0
4,4,0,3,1,35,0,0,8,2,1,1

In [88]:
X=df.drop('survived',axis=1)
y=df['survived']

In [89]:
from sklearn.model_selection import train_test_split

X_train,X_test ,y_train,y_test=train_test_split(X,y,test_size=0.2,
                                                random_state=42)

In [90]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [91]:
y_pred=model.predict(X_test)

In [92]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0])

In [93]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [94]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [95]:
accuracy_score(y_test,y_pred)

0.8033707865168539

In [96]:
confusion_matrix(y_test,y_pred)

array([[93, 16],
       [19, 50]])

In [97]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84       109
           1       0.76      0.72      0.74        69

    accuracy                           0.80       178
   macro avg       0.79      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178

In [98]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [99]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [100]:
from sklearn.neighbors import KNeighborsClassifier

In [101]:
knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [102]:
y_pred_knn =knn_model.predict(X_test_scaled)

In [103]:
accuracy_score(y_test,y_pred_knn)

0.797752808988764

In [104]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.83      0.84      0.84       109
           1       0.75      0.72      0.74        69

    accuracy                           0.80       178
   macro avg       0.79      0.78      0.79       178
weighted avg       0.80      0.80      0.80       178

In [105]:
confusion_matrix(y_test,y_pred_knn)

array([[92, 17],
       [19, 50]])

In [106]:
from  sklearn.naive_bayes import GaussianNB

In [107]:
modle_NB=GaussianNB()

In [108]:
modle_NB.fit(X_train,y_train)

GaussianNB()

In [109]:
y_pred_NB=modle_NB.predict(X_test)

In [110]:
y_pred_NB

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1])

In [111]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [112]:
accuracy_score(y_test,y_pred_NB)

0.8089887640449438

In [113]:
confusion_matrix(y_test,y_pred_NB)

array([[88, 21],
       [13, 56]])

In [114]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       0.87      0.81      0.84       109
           1       0.73      0.81      0.77        69

    accuracy                           0.81       178
   macro avg       0.80      0.81      0.80       178
weighted avg       0.82      0.81      0.81       178

In [115]:
from sklearn.tree import DecisionTreeClassifier

In [116]:
model_DT= DecisionTreeClassifier(random_state=42)

In [117]:
model_DT.fit(X_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [118]:
y_predDT=model_DT.predict(X_test_scaled)

In [119]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0])

In [120]:
accuracy_score(y_test,y_predDT)

0.7471910112359551

In [121]:
confusion_matrix(y_test,y_predDT)

array([[83, 26],
       [19, 50]])

In [122]:
print(classification_report(y_test,y_predDT))

              precision    recall  f1-score   support

           0       0.81      0.76      0.79       109
           1       0.66      0.72      0.69        69

    accuracy                           0.75       178
   macro avg       0.74      0.74      0.74       178
weighted avg       0.75      0.75      0.75       178

In [123]:
from sklearn.svm import SVC

In [124]:
model_svm =SVC(kernel='rbf')

In [125]:
model_svm.fit(X_train_scaled,y_train)

SVC()

In [126]:
y_pred_svc=model_svm.predict(X_test_scaled)

In [127]:
y_pred_svc

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [128]:
accuracy_score(y_test,y_pred_svc)

0.8202247191011236

In [129]:
confusion_matrix(y_test,y_pred_svc)

array([[92, 17],
       [15, 54]])

In [130]:
print(classification_report(y_test,y_pred_svc))

              precision    recall  f1-score   support

           0       0.86      0.84      0.85       109
           1       0.76      0.78      0.77        69

    accuracy                           0.82       178
   macro avg       0.81      0.81      0.81       178
weighted avg       0.82      0.82      0.82       178

In [131]:
from sklearn.model_selection import cross_val_score

In [132]:
scaler=StandardScaler()
X_scaled= scaler.fit_transform(X)

In [133]:
scores =cross_val_score(model_svm,X_scaled,y,cv=5,scoring='accuracy')

In [134]:
print(scores)

[0.83146067 0.82022472 0.82022472 0.80898876 0.85310734]

In [136]:
print(scores.mean())

0.8268012442074525